---

routers:
  - desc: sample-router
    re_id: 10.0.0.5  # Router entity id. (=router-id)
    datapath: sample_sw
    ports:
      - { name: 0/eth1,     port: 1 } # nid=0, lxc-iface=eth1, dp-port=1
      - { name: 0/eth2,     port: 2 } # nid=0, lxc-iface=eth2, dp-port=2
      - { name: 0/eth3,     port: 3 } # nid=0, lxc-iface=eth3, dp-port=3
      - { name: 0/eth4,     port: 4 } # nid=0, lxc-iface=eth4, dp-port=4
      - { name: 0/eth4.10,  port: 0,  link: "0/eth4" } # vlan iface of "0/eth4"
