---

filesdir: "roles/sample-net/files/{{ lxcname }}"

config_files:
  - { src: "interfaces.cfg", dst: "/etc/network/interfaces.d/50-beluganos.cfg", owner: "root" }
  - { src: "sysctl.conf",    dst: "/etc/sysctl.d/30-beluganos.conf", owner: "root" }
  - { src: "sysctl.service", dst: "/etc/systemd/system/beluganos.service", owner: "root" }
  - { src: "daemons",        dst: "/etc/frr/daemons",            owner: "frr" }
  - { src: "frr.conf",       dst: "/etc/frr/frr.conf",           owner: "frr" }

ovs_bridge: dp1

ovs_ports:
  - { name: "sample-p2.1", port_no: 1 }
  - { name: "sample-p3.1", port_no: 2 }
  - { name: "sample-p4.1", port_no: 3 }
