---

- import_tasks: "roles/sample-net/files/{{ lxcname }}/lxd_profile.yml"

- name: create container
  lxd_container:
    name: "{{ lxcname }}"
    state: started
    source:
      type: image
      alias: base
    profiles: ["{{ lxcname }}"]
