---

- include: "{{ filesdir }}/lxd_profile.yml"

- name: create container
  lxd_container:
    name: "{{ lxcname }}"
    state: started
    source:
      type: image
      alias: base
    profiles: ["{{ lxcname }}"]


- name: copy fibc.yml
  become: yes
  copy:
    src: "{{ filesdir }}/fibc.yml"
    dest: "{{ confdir }}/fibc.d/fibc-lxc-{{ lxcname }}.yml"
